### ISSUE TITLE
Login with "admin "admin" fails after initial installation

### ISSUE THREAD

**Issue by wolfskaempf** [eyp-developers/eyp-member-database#1]
Version: v1.0.1
Environment: [Scotch-box vagrant environment](https://box.scotch.io)

After first installing the software in a clean virtual machine with a LAMP stack and configuring the database in the configuration file, the first login using the initial "admin" "admin" combination fails.

After submitting the username and password, the page reloads and the user is greeted with the login screen once again. This behaviour could be infinitely repeated in our case.

**Comment by wolfskaempf** [comment]
Awesome project! Saw a demonstration by @samuelhoenle at the Summer Academy. Great work!

**Comment by davidrauch** [comment]
Can you check which response you get from the server after login? That might help me track down the bug.

**Comment by wolfskaempf** [comment]
The testing was done on a Surface which belongs to @rasmuskriest, so perhaps he can share that information with us? I'm afraid though he already deleted the virtual machine.

**Comment by rasmuskriest** [comment]
I was able to recover the box and replicate the issue. This is what a network analysis in Chrome results in during a failing login:

![image](https://cloud.githubusercontent.com/assets/7937072/18818547/1e7cc44a-837c-11e6-99a7-f611a5ea913b.png)

**Comment by davidrauch** [comment]
This issue is fixed in v1.0.2

**Comment by wolfskaempf** [comment]
Do you know what caused it?

**Comment by davidrauch** [comment]
Some webservers filter HTTP headers containing an underscore. The authentication token was sent in a header called "auth_token", so it never reached the application. Renaming the header fixed the issue.
