### ISSUE TITLE
Consider adding a License to your project

### ISSUE THREAD

**Issue by wolfskaempf** [eyp-developers/eyp-member-database#2]
Currently, the project is unlicensed, to technically nobody has the right to actually use or modify the code. You could consider adding a license to the project to clarify what is allowed and not allowed with your code.

[This website](http://choosealicense.com/) can help you choose the license you want.

Thanks for the awesome project!

**Comment by davidrauch** [comment]
Thanks for the reminder! I always just consider everything I write privately to be under [WTFPL](http://www.wtfpl.net), but that might not be appropriate here 😄

I added a copy to the MIT license.
